[asterisk-crm]
enabled  = true
filter   = asterisk-crm
logpath  = /var/log/asterisk/security
           /var/log/asterisk/messages
maxretry = 5
findtime = 300
bantime  = 3600
action   = iptables-allports[name=asterisk, protocol=all]
