[modules]
autoload = yes

; Отключаем неиспользуемые/опасные модули
noload => chan_sip.so           ; используем только PJSIP
noload => chan_dahdi.so
noload => chan_mgcp.so
noload => chan_skinny.so
noload => chan_unistim.so
noload => res_config_curl.so
noload => res_config_ldap.so
noload => res_xmpp.so
noload => chan_motif.so
