[Definition]
# Матчит неудачные SIP-аутентификации из лога Asterisk
failregex = ^\[<HOST>\] Registration from '.*' failed for '.*' - Wrong password$
            ^\[<HOST>\] Registration from '.*' failed for '.*' - No matching peer found$
            ^NOTICE.* <HOST> .*: Registration from '.*' failed for '<HOST>.*' - Wrong password$
            ^NOTICE.* <HOST> .*: Registration from '.*' failed for '<HOST>.*' - No matching peer found$
            ^NOTICE.* <HOST> .*failed for '<HOST>:.*' - Username/auth name mismatch$
            ^NOTICE.* <HOST> .*failed for '<HOST>:.*' - Device does not match ACL$
            ^NOTICE.* <HOST> .*: Sending fake auth rejection.*<HOST>

ignoreregex =
